<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-04-29 06:37
=======
# Generated by Django 3.0.5 on 2020-04-29 06:42
>>>>>>> 148f48595b191e18f935c923669eff9392d33199

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'Categorie',
=======
                'verbose_name': 'Category',
>>>>>>> 148f48595b191e18f935c923669eff9392d33199
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='uploads/items')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Product')),
            ],
        ),
    ]
