# Generated by Django 3.0.5 on 2020-04-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20200429_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
