# Generated by Django 3.0.5 on 2020-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_auto_20200429_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_added',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
