# Generated by Django 3.0.5 on 2020-04-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_item_quantity_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
    ]
