# Generated by Django 3.0.5 on 2020-04-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_remove_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ItemGroup',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_added',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='products_app.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.User')),
            ],
        ),
    ]
