# Generated by Django 3.0.5 on 2020-04-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_auto_20200430_0617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemGroup',
            new_name='Product',
        ),
    ]
